### ISSUE TITLE
Пагінація

### ISSUE THREAD

**Issue by amarsik1** [NikolasGumenyuk/my-react-table-v2#2]
- [x] бажина: дісейблить кнопку "предидуща" на першій сторінці
- [x] бажина: дісейблить кнопку "слєдуща" на останній сторінці
- [x] огранічить колічество кнопок в пагінації

Приклад: [моя табличка](https://table-vue-amarsik1.netlify.app), тикнеш тіки пагінацію вкл

**Comment by NikolasGumenyuk** [comment]
fix pagination

**Comment by NikolasGumenyuk** [comment]
[https://github.com/NikolasGumenyuk/my-react-table-v2/pull/4](url)
